package autoplant.ui.graphic.action;

import autoplant.business.OperationService;
import autoplant.business.domain.UnidadeDeCultivo;

/**
 *
 * @author gbljunior
 */
public class InsertAction extends javax.swing.JFrame {
    
    private final OperationService operationService;
    private final Integer id;

    /**
     * Creates new form InsertAction
     */
    public InsertAction(OperationService operationService) {
        this.operationService = operationService;
        this.id = 0;
        initComponents();
    }
    
    public InsertAction(OperationService operationService, UnidadeDeCultivo unidadeDeCultivo) {
        this.operationService = operationService;
        this.id = unidadeDeCultivo.getId();
        initComponents();
        initData(unidadeDeCultivo);
        nomeCultivo.setEditable(false);
        semente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIdentificacao = new javax.swing.JLabel();
        jLNomeCultivo = new javax.swing.JLabel();
        nomeCultivo = new javax.swing.JTextField();
        jLSemente = new javax.swing.JLabel();
        semente = new javax.swing.JTextField();
        jLMetas = new javax.swing.JLabel();
        jLK = new javax.swing.JLabel();
        metaK = new javax.swing.JTextField();
        jLCa = new javax.swing.JLabel();
        metaCa = new javax.swing.JTextField();
        jLN = new javax.swing.JLabel();
        metaN = new javax.swing.JTextField();
        jLU = new javax.swing.JLabel();
        metaUmidade = new javax.swing.JTextField();
        jLL = new javax.swing.JLabel();
        metaLuminosidade = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLIdentificacao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLIdentificacao.setText("Identificação");

        jLNomeCultivo.setText("Nome do Cultivo:");

        nomeCultivo.setBackground(new java.awt.Color(200, 200, 200));

        jLSemente.setText("Semente:");

        semente.setBackground(new java.awt.Color(200, 200, 200));

        jLMetas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLMetas.setText("Metas");

        jLK.setText("Concentração(K):");

        metaK.setBackground(new java.awt.Color(200, 200, 200));

        jLCa.setText("Concentração(Ca):");

        metaCa.setBackground(new java.awt.Color(200, 200, 200));

        jLN.setText("Concentração(N):");

        metaN.setBackground(new java.awt.Color(200, 200, 200));

        jLU.setText("Umidade:");

        metaUmidade.setBackground(new java.awt.Color(200, 200, 200));
        metaUmidade.setToolTipText("");

        jLL.setText("Luminosidade:");

        metaLuminosidade.setBackground(new java.awt.Color(200, 200, 200));

        confirm.setBackground(new java.awt.Color(195, 220, 195));
        confirm.setText("Confirmar");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLIdentificacao)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNomeCultivo)
                            .addComponent(jLSemente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLMetas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLK)
                            .addComponent(jLCa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(metaK)
                            .addComponent(metaCa, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(metaN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLL)
                            .addComponent(jLU))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(metaUmidade)
                            .addComponent(metaLuminosidade, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIdentificacao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeCultivo)
                    .addComponent(nomeCultivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSemente)
                    .addComponent(semente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLMetas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLK)
                    .addComponent(metaK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCa)
                    .addComponent(metaCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLN)
                    .addComponent(metaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLU)
                    .addComponent(metaUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLL)
                    .addComponent(metaLuminosidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isFormComplete(){
        return !nomeCultivo.getText().isEmpty() && !semente.getText().isEmpty() && !metaK.getText().isEmpty() && !metaCa.getText().isEmpty() && !metaN.getText().isEmpty() && !metaUmidade.getText().isEmpty() && !metaUmidade.getText().isEmpty();
    }
    
    private void initData(UnidadeDeCultivo uc){
        nomeCultivo.setText(uc.getNomeCultivo());
        semente.setText(uc.getPlanta().getSemente());
        metaK.setText(uc.getMetaPotassio().toString());
        metaCa.setText(uc.getMetaCalcio().toString());
        metaN.setText(uc.getMetaNitrogenio().toString());
        metaUmidade.setText(uc.getMetaUmidade().toString());
        metaLuminosidade.setText(uc.getMetaLuminosidade().toString());
    }
    
    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        if(isFormComplete()){
            if (id == 0){
                try {
                    UnidadeDeCultivo uc = operationService.insertUnidadeDeCultivo(nomeCultivo.getText(), semente.getText(), metaK.getText(), metaCa.getText(), metaN.getText(), metaUmidade.getText(), metaLuminosidade.getText());
                    VisualizeAction action = new VisualizeAction(uc);
                    action.setVisible(true);
                    dispose();
                } catch (Exception e) {
                }
            }
            else{
                try {
                    UnidadeDeCultivo uc = operationService.insertUnidadeDeCultivo(id, metaK.getText(), metaCa.getText(), metaN.getText(), metaUmidade.getText(), metaLuminosidade.getText());
                    dispose();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_confirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLCa;
    private javax.swing.JLabel jLIdentificacao;
    private javax.swing.JLabel jLK;
    private javax.swing.JLabel jLL;
    private javax.swing.JLabel jLMetas;
    private javax.swing.JLabel jLN;
    private javax.swing.JLabel jLNomeCultivo;
    private javax.swing.JLabel jLSemente;
    private javax.swing.JLabel jLU;
    private javax.swing.JTextField metaCa;
    private javax.swing.JTextField metaK;
    private javax.swing.JTextField metaLuminosidade;
    private javax.swing.JTextField metaN;
    private javax.swing.JTextField metaUmidade;
    private javax.swing.JTextField nomeCultivo;
    private javax.swing.JTextField semente;
    // End of variables declaration//GEN-END:variables
}
