/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autoplant.ui.graphic.action;

import autoplant.business.domain.UnidadeDeCultivo;

/**
 *
 * @author gbljunior
 */
public class VisualizeAction extends javax.swing.JFrame {

    private final UnidadeDeCultivo uc;
    /**
     * Creates new form VisualizeAction
     */
    public VisualizeAction(UnidadeDeCultivo uc) {
        this.uc = uc;
        
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeCultivo = new javax.swing.JLabel();
        jLSemente = new javax.swing.JLabel();
        semente = new javax.swing.JLabel();
        jLLuminosidade = new javax.swing.JLabel();
        luminosidade = new javax.swing.JLabel();
        jLUmidade = new javax.swing.JLabel();
        umidade = new javax.swing.JLabel();
        jLPotassio = new javax.swing.JLabel();
        potassio = new javax.swing.JLabel();
        jLCalcio = new javax.swing.JLabel();
        calcio = new javax.swing.JLabel();
        jLNitrogenio = new javax.swing.JLabel();
        nitrogenio = new javax.swing.JLabel();
        totalUmidade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalPotassio = new javax.swing.JLabel();
        jLTP = new javax.swing.JLabel();
        totalCalcio = new javax.swing.JLabel();
        jLTC = new javax.swing.JLabel();
        totalNitrogenio = new javax.swing.JLabel();
        jLTN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeCultivo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeCultivo.setText("Nome do Cultivo");

        jLSemente.setText("Semente:");

        semente.setText("float");

        jLLuminosidade.setText("Luminosidade:");

        luminosidade.setText("float");

        jLUmidade.setText("Umidade do Solo:");

        umidade.setText("float");

        jLPotassio.setText("Concentração de Potássio:");

        potassio.setText("float");

        jLCalcio.setText("Concentração de Cálcio:");

        calcio.setText("float");

        jLNitrogenio.setText("Concentração de Nitrogenio:");

        nitrogenio.setText("float");

        totalUmidade.setText("float");

        jLabel2.setText("Volume Irrigado:");

        totalPotassio.setText("float");

        jLTP.setText("Qtd Fertilizante:");

        totalCalcio.setText("float");

        jLTC.setText("Qtd Fertilizante:");

        totalNitrogenio.setText("float");

        jLTN.setText("Qtd Fertilizante:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNitrogenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nitrogenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(jLTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalNitrogenio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCalcio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalCalcio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLPotassio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potassio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPotassio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLUmidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(umidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalUmidade))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLSemente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(semente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLLuminosidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(luminosidade))
                            .addComponent(nomeCultivo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeCultivo)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSemente)
                    .addComponent(semente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLuminosidade)
                    .addComponent(luminosidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUmidade)
                    .addComponent(umidade)
                    .addComponent(totalUmidade)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPotassio)
                    .addComponent(potassio)
                    .addComponent(totalPotassio)
                    .addComponent(jLTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCalcio)
                    .addComponent(calcio)
                    .addComponent(totalCalcio)
                    .addComponent(jLTC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNitrogenio)
                    .addComponent(nitrogenio)
                    .addComponent(totalNitrogenio)
                    .addComponent(jLTN))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initData(){
        nomeCultivo.setText(uc.getNomeCultivo());
        semente.setText(uc.getPlanta().getSemente());
        luminosidade.setText(uc.getPlanta().getNivelLuminosidade().toString());
        umidade.setText(uc.getPlanta().getUmidadeDoSolo().toString());
        potassio.setText(uc.getPlanta().getTeorPotassio().toString());
        calcio.setText(uc.getPlanta().getTeorCalcio().toString());
        nitrogenio.setText(uc.getPlanta().getTeorNitrogenio().toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcio;
    private javax.swing.JLabel jLCalcio;
    private javax.swing.JLabel jLLuminosidade;
    private javax.swing.JLabel jLNitrogenio;
    private javax.swing.JLabel jLPotassio;
    private javax.swing.JLabel jLSemente;
    private javax.swing.JLabel jLTC;
    private javax.swing.JLabel jLTN;
    private javax.swing.JLabel jLTP;
    private javax.swing.JLabel jLUmidade;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel luminosidade;
    private javax.swing.JLabel nitrogenio;
    private javax.swing.JLabel nomeCultivo;
    private javax.swing.JLabel potassio;
    private javax.swing.JLabel semente;
    private javax.swing.JLabel totalCalcio;
    private javax.swing.JLabel totalNitrogenio;
    private javax.swing.JLabel totalPotassio;
    private javax.swing.JLabel totalUmidade;
    private javax.swing.JLabel umidade;
    // End of variables declaration//GEN-END:variables
}
